name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint (flake8 minimal)
        run: |
          pip install flake8
          flake8 app mocks || true
      - name: Build Agent image
        run: |
          docker build -f infra/agent.Dockerfile -t agentops-mock:ci .
